package cn.edu.sustech.cs209.chatting.common;

public enum MessageType {
  CONNECT,DISCONNECT,MSG,QUERY,SUCCESS,FAIL,USERLIST,NOTIFICATION,SINGLE,SINGLEREQUIRE,
  CHATSHEETNEW,QUERYCHAT,QUERYMSG,QUERYCHATSHEET,FINDONRQUERYMEMBER,FILE
}